import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  devSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Core',
      items: [
        'core/project-overview',
        'core/runtime-architecture',
        'core/database-and-tenancy',
        'core/frontend-dashboard',
        'core/release-and-versioning',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'category',
          label: 'Service Split',
          items: [
            'modules/platform-api',
            'modules/billing-api',
            'modules/ecommerce-api',
            'modules/billing-app',
            'modules/ecommerce-app',
            'modules/crm-app',
            'modules/sites-app',
            'modules/cxsync-app',
          ],
        },
        'modules/auth',
        'modules/tenant',
        'modules/tenant-domain',
        'modules/industry',
        'modules/app-setup',
        'modules/system-update',
        'modules/queue-manager',
        'modules/database-manager',
        'modules/site',
        'modules/company',
        'modules/contact',
        'modules/product',
        'modules/order',
        'modules/common',
        'modules/billing-entries',
        'modules/billing-reports',
        'modules/accounts',
        'modules/inventory-stock',
        'modules/settings',
        'modules/gst-compliance',
        'modules/media',
        'modules/mail',
        'modules/task-manager',
        'modules/crm',
        'modules/tally',
        'modules/frappe',
        'modules/tconnect',
        'modules/ecommerce',
        'modules/auditor',
        'modules/blog',
        'modules/agent-os',
      ],
    },
  ],
}

export default sidebars
