import { contextBridge, ipcRenderer } from "electron"
import type {
  CxSyncDesktopApi,
  LocalAdminSession,
  LocalEnvironmentStatus,
  TenantConnection,
  TenantCloudSnapshot,
  TenantDatabaseInspection,
  TenantHandshakeHistoryItem,
  TenantSchemaBaseline,
  TenantSchemaBuildStatus,
  TenantSchemaDiffResult,
  TenantUpgradePlan,
  TenantUpgradePreflight,
  TenantUpgradeExecution,
  TenantBackupRecord,
  TenantConnectionInput,
  TenantConnectionVerification,
} from "../../src/shared/connection-contracts.js"

const api: CxSyncDesktopApi = {
  isDesktop: true,
  authenticateLocalAdmin: (email: string, password: string) => ipcRenderer.invoke("cxsync:auth:login", email, password) as Promise<LocalAdminSession>,
  captureCodebaseSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:capture-codebase", id) as Promise<TenantSchemaBaseline>,
  captureTenantSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:capture", id) as Promise<TenantSchemaBaseline>,
  compareTenantSchema: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-diff", id) as Promise<TenantSchemaDiffResult>,
  deleteTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:delete", id) as Promise<void>,
  getLocalEnvironmentStatus: () => ipcRenderer.invoke("cxsync:environment:status") as Promise<LocalEnvironmentStatus>,
  getTenantSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline", id) as Promise<TenantSchemaBaseline | null>,
  getCodebaseSchemaBuildStatus: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:build-status", id) as Promise<TenantSchemaBuildStatus>,
  getTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:get", id) as Promise<TenantConnection | null>,
  getTenantCloudSnapshot: (id: string) => ipcRenderer.invoke("cxsync:tenants:cloud-snapshot", id) as Promise<TenantCloudSnapshot | null>,
  getTenantUpgradePlan: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-plan", id) as Promise<TenantUpgradePlan | null>,
  generateTenantUpgradePlan: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-plan:generate", id) as Promise<TenantUpgradePlan>,
  getTenantUpgradePreflight: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-preflight", id) as Promise<TenantUpgradePreflight | null>,
  runTenantUpgradePreflight: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-preflight:run", id) as Promise<TenantUpgradePreflight>,
  getTenantUpgradeExecution: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-execution", id) as Promise<TenantUpgradeExecution | null>,
  executeTenantUpgrade: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-execution:run", id) as Promise<TenantUpgradeExecution>,
  createTenantBackup: (id: string) => ipcRenderer.invoke("cxsync:tenants:backup:create", id) as Promise<TenantBackupRecord>,
  getTenantBackup: (id: string) => ipcRenderer.invoke("cxsync:tenants:backup", id) as Promise<TenantBackupRecord | null>,
  inspectTenantDatabase: (id: string) => ipcRenderer.invoke("cxsync:tenants:inspect", id) as Promise<TenantDatabaseInspection>,
  listTenantHandshakeHistory: (id: string) => ipcRenderer.invoke("cxsync:tenants:history", id) as Promise<TenantHandshakeHistoryItem[]>,
  listTenantConnections: () => ipcRenderer.invoke("cxsync:tenants:list") as Promise<TenantConnection[]>,
  saveTenantConnection: (input: TenantConnectionInput, id?: string) => ipcRenderer.invoke("cxsync:tenants:save", input, id) as Promise<TenantConnection>,
  captureTenantCloudSnapshot: (id: string) => ipcRenderer.invoke("cxsync:tenants:cloud-snapshot:capture", id) as Promise<TenantCloudSnapshot>,
  verifyTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:verify", id) as Promise<TenantConnectionVerification>,
}

contextBridge.exposeInMainWorld("cxsyncDesktop", api)
