import { contextBridge, ipcRenderer } from "electron"
import type {
  CxSyncDesktopApi,
  CxSyncGeneratedServiceKey,
  CxSyncCloudServiceHandshake,
  CxSyncServiceKeyStatus,
  LocalAdminSession,
  LocalEnvironmentStatus,
  TenantConnection,
  TenantCloudSnapshot,
  TenantDatabaseInspection,
  TenantHandshakeHistoryItem,
  TenantSchemaBaseline,
  TenantSchemaBuildStatus,
  TenantSchemaDiffResult,
  TenantSyncJob,
  TenantSyncReportExport,
  TenantSyncServiceStatus,
  TenantUpgradePlan,
  TenantUpgradePreflight,
  TenantUpgradeExecution,
  TenantBackupRecord,
  TenantConnectionInput,
  TenantConnectionVerification,
  SqlDumpCredentials,
  SqlDumpJob,
  SqlDumpTable,
  SqlDumpDatabase,
  SqlDumpQueue,
  SqlDumpServerCredentials,
  CloudDiagnostics,
} from "../../src/shared/connection-contracts.js"

const api: CxSyncDesktopApi = {
  isDesktop: true,
  authenticateLocalAdmin: (email: string, password: string) => ipcRenderer.invoke("cxsync:auth:login", email, password) as Promise<LocalAdminSession>,
  captureCodebaseSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:capture-codebase", id) as Promise<TenantSchemaBaseline>,
  captureTenantSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:capture", id) as Promise<TenantSchemaBaseline>,
  compareTenantSchema: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-diff", id) as Promise<TenantSchemaDiffResult>,
  deleteTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:delete", id) as Promise<void>,
  getLocalEnvironmentStatus: () => ipcRenderer.invoke("cxsync:environment:status") as Promise<LocalEnvironmentStatus>,
  getServiceKeyStatus: () => ipcRenderer.invoke("cxsync:service-key:status") as Promise<CxSyncServiceKeyStatus>,
  generateServiceKey: () => ipcRenderer.invoke("cxsync:service-key:generate") as Promise<CxSyncGeneratedServiceKey>,
  saveServiceKey: (key: string) => ipcRenderer.invoke("cxsync:service-key:save", key) as Promise<CxSyncServiceKeyStatus>,
  saveCloudServiceUrl: (url: string) => ipcRenderer.invoke("cxsync:cloud-service:url:save", url) as Promise<CxSyncServiceKeyStatus>,
  getCloudServiceHandshake: () => ipcRenderer.invoke("cxsync:cloud-service:handshake") as Promise<CxSyncCloudServiceHandshake | null>,
  verifyCloudServiceHandshake: () => ipcRenderer.invoke("cxsync:cloud-service:handshake:verify") as Promise<CxSyncCloudServiceHandshake>,
  runCloudDiagnostics: () => ipcRenderer.invoke("cxsync:cloud-service:diagnostics") as Promise<CloudDiagnostics>,
  getTenantSchemaBaseline: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline", id) as Promise<TenantSchemaBaseline | null>,
  getCodebaseSchemaBuildStatus: (id: string) => ipcRenderer.invoke("cxsync:tenants:schema-baseline:build-status", id) as Promise<TenantSchemaBuildStatus>,
  getTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:get", id) as Promise<TenantConnection | null>,
  getTenantCloudSnapshot: (id: string) => ipcRenderer.invoke("cxsync:tenants:cloud-snapshot", id) as Promise<TenantCloudSnapshot | null>,
  getTenantUpgradePlan: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-plan", id) as Promise<TenantUpgradePlan | null>,
  generateTenantUpgradePlan: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-plan:generate", id) as Promise<TenantUpgradePlan>,
  getTenantUpgradePreflight: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-preflight", id) as Promise<TenantUpgradePreflight | null>,
  runTenantUpgradePreflight: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-preflight:run", id) as Promise<TenantUpgradePreflight>,
  getTenantUpgradeExecution: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-execution", id) as Promise<TenantUpgradeExecution | null>,
  getTenantSyncJob: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-job", id) as Promise<TenantSyncJob | null>,
  listTenantSyncJobs: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-jobs", id) as Promise<TenantSyncJob[]>,
  checkTenantSyncService: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-service:check", id) as Promise<TenantSyncServiceStatus>,
  exportTenantSyncReport: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-report:export", id) as Promise<TenantSyncReportExport>,
  executeTenantUpgrade: (id: string) => ipcRenderer.invoke("cxsync:tenants:upgrade-execution:run", id) as Promise<TenantUpgradeExecution>,
  runTenantSyncJob: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-job:run", id) as Promise<TenantSyncJob>,
  continueTenantSyncJob: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-job:continue", id) as Promise<TenantSyncJob>,
  retryTenantSyncJob: (id: string) => ipcRenderer.invoke("cxsync:tenants:sync-job:retry", id) as Promise<TenantSyncJob>,
  createTenantBackup: (id: string) => ipcRenderer.invoke("cxsync:tenants:backup:create", id) as Promise<TenantBackupRecord>,
  getTenantBackup: (id: string) => ipcRenderer.invoke("cxsync:tenants:backup", id) as Promise<TenantBackupRecord | null>,
  inspectTenantDatabase: (id: string) => ipcRenderer.invoke("cxsync:tenants:inspect", id) as Promise<TenantDatabaseInspection>,
  listTenantHandshakeHistory: (id: string) => ipcRenderer.invoke("cxsync:tenants:history", id) as Promise<TenantHandshakeHistoryItem[]>,
  listTenantConnections: () => ipcRenderer.invoke("cxsync:tenants:list") as Promise<TenantConnection[]>,
  saveTenantConnection: (input: TenantConnectionInput, id?: string) => ipcRenderer.invoke("cxsync:tenants:save", input, id) as Promise<TenantConnection>,
  captureTenantCloudSnapshot: (id: string) => ipcRenderer.invoke("cxsync:tenants:cloud-snapshot:capture", id) as Promise<TenantCloudSnapshot>,
  verifyTenantConnection: (id: string) => ipcRenderer.invoke("cxsync:tenants:verify", id) as Promise<TenantConnectionVerification>,
  chooseSqlDumpDirectory: () => ipcRenderer.invoke("cxsync:sql-dump:directory:choose") as Promise<string | null>,
  listSqlDumpDatabases: (credentials: SqlDumpServerCredentials) => ipcRenderer.invoke("cxsync:sql-dump:databases", credentials) as Promise<SqlDumpDatabase[]>,
  inspectSqlDumpTables: (credentials: SqlDumpCredentials) => ipcRenderer.invoke("cxsync:sql-dump:tables", credentials) as Promise<SqlDumpTable[]>,
  startSqlDump: (credentials: SqlDumpCredentials, destination: string) => ipcRenderer.invoke("cxsync:sql-dump:start", credentials, destination) as Promise<SqlDumpJob>,
  getSqlDumpJob: (id: string) => ipcRenderer.invoke("cxsync:sql-dump:job", id) as Promise<SqlDumpJob | null>,
  startSqlDumpQueue: (credentials: SqlDumpServerCredentials, databases: string[], destination: string) => ipcRenderer.invoke("cxsync:sql-dump:queue:start", credentials, databases, destination) as Promise<SqlDumpQueue>,
  getSqlDumpQueue: (id: string) => ipcRenderer.invoke("cxsync:sql-dump:queue", id) as Promise<SqlDumpQueue | null>,
}

contextBridge.exposeInMainWorld("cxsyncDesktop", api)
