import qrcode from "qrcode-generator"
import type { ReactNode } from "react"
import type { CompanyRecord } from "src/features/company/company-client"
import type { GstComplianceDocument } from "src/features/gst/gst-compliance-client"
import { createCode128BarcodeSvg } from "./sales-barcode"
import type { SalesEntry } from "./sales-client"
import type { SalesPrintPartyDetails } from "./sales-print-page"

interface SalesEwayBillDocumentProps {
  readonly billingParty?: SalesPrintPartyDetails | null
  readonly company: CompanyRecord | null
  readonly document?: GstComplianceDocument | null
  readonly record: SalesEntry
  readonly shippingParty?: SalesPrintPartyDetails | null
}

const tableClass = "w-full border-collapse border border-[#9a9a9a]"
const labelCell = "w-[35.5%] border border-[#9a9a9a] px-1.5 py-[7px] align-middle font-normal"
const valueCell = "border border-[#9a9a9a] px-1.5 py-[7px] align-middle font-bold"
const sectionCell = "border border-[#9a9a9a] px-1.5 py-[7px] font-bold"

export function SalesEwayBillDocument({ billingParty, company, document, record, shippingParty }: SalesEwayBillDocumentProps) {
  const ewayBillNo = printableText(document?.ewayBillNo) || printableText(record.eway_bill_no)
  const ewayBillNoPlain = ewayBillNo.replace(/\s+/g, "")
  const ewayBillDate = printableText(document?.ewayBillDate) || printableText(record.eway_bill_date)
  const validUntil = printableText(document?.ewayValidUpto)
  const companyName = printableText(company?.legalName) || printableText(company?.name) || "Company"
  const companyGstin = printableText(company?.gstinUin)
  const supplierValue = [companyGstin, companyName].filter(Boolean).join(",")
  const recipientGstin = printableText(record.customer_gstin) || "URP"
  const recipientValue = [recipientGstin, printableText(record.customer_name) || "Customer"].filter(Boolean).join(" ,")
  const dispatch = companyDispatchLine(company)
  const delivery = partyPlaceLine(shippingParty) || partyPlaceLine(billingParty)
  const hsnCodes = ewayHsnCodes(record)
  const fromPlace = firstLocation(dispatch) || firstLocation(delivery)
  const enteredBy = companyGstin || "-"
  const vehicleNo = printableText(record.vehicle_no)
  const transporter = [printableText(record.transport_gst), printableText(record.transport_name)].filter(Boolean).join(",")
  const qrValue = ewayQrPayload({ companyGstin, ewayBillDate, ewayBillNo: ewayBillNoPlain, invoiceNo: record.invoice_no, total: record.grand_total })

  return (
    <section className="sales-eway-print-page mx-auto w-[210mm] max-w-full bg-white p-[4mm] font-[Arial,Helvetica,sans-serif] text-[13px] leading-tight text-black print:w-[198mm] print:max-w-none print:p-0">
      <div className="border border-[#9a9a9a]">
        <div className="grid min-h-[38mm] place-items-center border-b border-[#9a9a9a] py-2">
          <div className="text-center">
            <h1 className="text-[22px] font-bold leading-none">e-Way Bill</h1>
            <div className="mx-auto mt-3 h-[31mm] w-[31mm]">{qrValue ? <QrCode value={qrValue} /> : null}</div>
          </div>
        </div>

        <table className={tableClass}>
          <tbody>
            <EwayDetailRow label="E-Way Bill No:" value={formatEwayNumber(ewayBillNo)} />
            <EwayDetailRow label="E-Way Bill Date:" value={formatEwayDateTime(ewayBillDate)} />
            <EwayDetailRow label="Generated By:" value={supplierValue || "-"} />
            <EwayDetailRow label="Valid From:" value={formatValidFrom(ewayBillDate, record)} />
            <EwayDetailRow label="Valid Until:" value={validUntil ? formatEwayDate(validUntil) : "-"} />
            <EwayDetailRow label="Portal:" value="1" />
            <tr><td className={sectionCell} colSpan={2}>Part - A</td></tr>
            <EwayDetailRow label="GSTIN of Supplier" value={supplierValue || "-"} />
            <EwayDetailRow label="Place of Dispatch" value={dispatch || "-"} />
            <EwayDetailRow label="GSTIN of Recipient" value={recipientValue || "-"} />
            <EwayDetailRow label="Place of Delivery" value={delivery || "-"} />
            <EwayDetailRow label="Document No." value={record.invoice_no || "-"} />
            <EwayDetailRow label="Document Date" value={formatEwayDate(record.invoice_date)} />
            <EwayDetailRow label="Transaction Type:" value="Regular" />
            <EwayDetailRow label="Value of Goods" value={ewayGoodsValue(record)} />
            <EwayDetailRow label="HSN Code" value={hsnCodes ? `${hsnCodes} -` : "-"} />
            <EwayDetailRow label="Reason for Transportation" value="Outward - Supply" />
            <EwayDetailRow label="Transporter" value={transporter || "-"} />
            <tr><td className={sectionCell} colSpan={2}>Part - B</td></tr>
          </tbody>
        </table>

        <div className="border-x border-[#9a9a9a] px-1.5 py-2">
          <table className="w-full border-collapse border border-[#9a9a9a]">
            <thead>
              <tr>
                <EwayPartBHeader>Mode</EwayPartBHeader>
                <EwayPartBHeader>Vehicle / Trans<br />Doc No &amp; Dt.</EwayPartBHeader>
                <EwayPartBHeader>From</EwayPartBHeader>
                <EwayPartBHeader>Entered Date</EwayPartBHeader>
                <EwayPartBHeader>Entered By</EwayPartBHeader>
                <EwayPartBHeader>CEWB No.<br />(If any)</EwayPartBHeader>
                <EwayPartBHeader>Multi Veh.Info<br />(If any)</EwayPartBHeader>
                <EwayPartBHeader>Portal</EwayPartBHeader>
              </tr>
            </thead>
            <tbody>
              <tr>
                <EwayPartBCell>Road</EwayPartBCell>
                <EwayPartBCell>{vehicleNo || "-"}</EwayPartBCell>
                <EwayPartBCell>{fromPlace || "-"}</EwayPartBCell>
                <EwayPartBCell>{formatEwayDateTime(ewayBillDate)}</EwayPartBCell>
                <EwayPartBCell>{enteredBy}</EwayPartBCell>
                <EwayPartBCell>-</EwayPartBCell>
                <EwayPartBCell>-</EwayPartBCell>
                <EwayPartBCell>1</EwayPartBCell>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="grid min-h-[21mm] place-items-center border-t border-[#9a9a9a] py-2">
          {ewayBillNoPlain ? <EwayBarcode value={ewayBillNoPlain} /> : null}
        </div>
        <div className="border-t border-[#9a9a9a] px-2 py-4 text-[11px]">
          <span className="font-bold">Note*:</span> If any discrepancy in information please try after sometimes.
        </div>
      </div>
    </section>
  )
}

function EwayDetailRow({ label, value }: { label: string; value: string }) {
  return (
    <tr>
      <td className={labelCell}>{label}</td>
      <td className={valueCell}>{value || "-"}</td>
    </tr>
  )
}

function EwayPartBHeader({ children }: { children: ReactNode }) {
  return <th className="border border-[#9a9a9a] px-1.5 py-3 text-left align-middle text-[13px] font-bold leading-tight">{children}</th>
}

function EwayPartBCell({ children }: { children: ReactNode }) {
  return <td className="border border-[#9a9a9a] px-1.5 py-3 align-middle text-[13px] leading-tight">{children}</td>
}

function QrCode({ value }: { value: string }) {
  const svgMarkup = createQrSvg(value)
  if (!svgMarkup) return null
  return <div className="size-full [&_svg]:block [&_svg]:size-full" dangerouslySetInnerHTML={{ __html: svgMarkup }} />
}

function EwayBarcode({ value }: { value: string }) {
  const svgMarkup = createCode128BarcodeSvg(value)
  if (!svgMarkup) return null
  return (
    <div className="w-[35mm]">
      <div className="h-[12mm] bg-white [&_svg]:block [&_svg]:h-full [&_svg]:w-full" dangerouslySetInnerHTML={{ __html: svgMarkup }} />
      <div className="mt-0.5 text-center font-mono text-[10px] leading-none">{value}</div>
    </div>
  )
}

function createQrSvg(value: string) {
  try {
    const qr = qrcode(0, "M")
    qr.addData(value)
    qr.make()
    return qr.createSvgTag({ cellSize: 2, margin: 1, scalable: true })
  } catch {
    try {
      const qr = qrcode(0, "L")
      qr.addData(value)
      qr.make()
      return qr.createSvgTag({ cellSize: 2, margin: 1, scalable: true })
    } catch {
      return ""
    }
  }
}

function companyDispatchLine(company: CompanyRecord | null) {
  const address = company?.addresses.find((item) => item.isDefault) ?? company?.addresses[0] ?? null
  if (!address) return ""
  const city = printableText(address.cityName)
  const state = printableText(address.stateName)
  const pincode = printableText(address.pincodeName)
  return [city, state].filter(Boolean).join(",").toUpperCase() + (pincode ? `-${pincode}` : "")
}

function partyPlaceLine(party?: SalesPrintPartyDetails | null) {
  const state = printableText(party?.stateName)
  const location = printableText(party?.locationLine)
  if (!location && !state) return ""
  const pincode = location.match(/\b\d{6}\b/)?.[0] ?? ""
  const city = location.split(/[-,]/)[0]?.trim() ?? ""
  return [city, state].filter(Boolean).join(",").toUpperCase() + (pincode ? `-${pincode}` : "")
}

function firstLocation(value: string) {
  return value.split(",")[0]?.split("-")[0]?.trim() ?? ""
}

function ewayHsnCodes(record: SalesEntry) {
  return Array.from(new Set(record.items.map((item) => printableText(item.hsn_code)).filter(Boolean))).join(", ")
}

function ewayGoodsValue(record: SalesEntry) {
  return String(Math.round(Number(record.grand_total || record.taxable_total || 0)))
}

function formatValidFrom(value: string, record: SalesEntry) {
  const formatted = formatEwayDateTime(value)
  if (formatted === "-") return "-"
  const distance = printableText((record as unknown as Record<string, unknown>).transport_distance)
  return distance ? `${formatted} [${distance}Kms]` : formatted
}

function ewayQrPayload(input: { companyGstin: string; ewayBillDate: string; ewayBillNo: string; invoiceNo: string; total: number }) {
  return [
    input.ewayBillNo,
    input.companyGstin,
    input.invoiceNo,
    formatEwayDate(input.ewayBillDate),
    Math.round(Number(input.total || 0)),
  ].filter(Boolean).join("|")
}

function formatEwayNumber(value: string) {
  const plain = value.replace(/\s+/g, "")
  return plain.length === 12 ? `${plain.slice(0, 4)} ${plain.slice(4, 8)} ${plain.slice(8)}` : value || "-"
}

function formatEwayDateTime(value?: string | null) {
  const date = parseDate(value)
  if (!date) return "-"
  const hasTime = /T|\d{1,2}:\d{2}/.test(String(value))
  if (!hasTime) return formatEwayDate(value)
  return new Intl.DateTimeFormat("en-IN", { day: "2-digit", hour: "2-digit", hour12: true, minute: "2-digit", month: "2-digit", year: "numeric" }).format(date).replace(",", "")
}

function formatEwayDate(value?: string | null) {
  const date = parseDate(value)
  if (!date) return "-"
  return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(date)
}

function parseDate(value?: string | null) {
  if (!value) return null
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? null : date
}

function printableText(value: unknown) {
  return typeof value === "string" ? value.trim() : value === null || value === undefined ? "" : String(value).trim()
}
