import type { MasterDataModuleDefinition } from '../../../../foundation/master-record/domain/value-objects/master-data-definition.js'

export const contactMasterDefinition: MasterDataModuleDefinition = {
  key: 'contacts',
  label: 'Contacts',
  kind: 'master',
  tableName: 'masters_contacts',
  defaultSortKey: 'name',
  idPrefix: 'contact',
  group: 'contacts',
  columns: [
    { key: 'code', label: 'Code', type: 'string', required: true, nullable: false },
    { key: 'name', label: 'Name', type: 'string', required: true, nullable: false },
    { key: 'contact_type_id', label: 'Contact Type', type: 'string', nullable: true },
    { key: 'ledger_id', label: 'Ledger', type: 'string', nullable: true },
    { key: 'ledger_name', label: 'Ledger Name', type: 'string', nullable: true },
    { key: 'legal_name', label: 'Legal Name', type: 'string', nullable: true },
    { key: 'pan', label: 'PAN', type: 'string', nullable: true },
    { key: 'gstin', label: 'GSTIN', type: 'string', nullable: true },
    { key: 'msme_type', label: 'MSME Type', type: 'string', nullable: true },
    { key: 'msme_no', label: 'MSME No', type: 'string', nullable: true },
    { key: 'tan', label: 'TAN', type: 'string', nullable: true },
    { key: 'tds_available', label: 'TDS Available', type: 'boolean', nullable: true },
    { key: 'tcs_available', label: 'TCS Available', type: 'boolean', nullable: true },
    { key: 'opening_balance', label: 'Opening Balance', type: 'number', numberMode: 'decimal', nullable: true },
    { key: 'balance_type', label: 'Balance Type', type: 'string', nullable: true },
    { key: 'credit_limit', label: 'Credit Limit', type: 'number', numberMode: 'decimal', nullable: true },
    { key: 'website', label: 'Website', type: 'string', nullable: true },
    { key: 'primary_email', label: 'Primary Email', type: 'string', nullable: true },
    { key: 'primary_phone', label: 'Primary Phone', type: 'string', nullable: true },
    { key: 'description', label: 'Description', type: 'string', nullable: true },
  ],
}
